"""phase 1: kana, learning sessions, daily plans, streaks, FSRS card step

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-06 04:19:50.545684
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_plans",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("new_items_target", sa.Integer(), nullable=False),
        sa.Column("due_count", sa.Integer(), nullable=False),
        sa.Column("retention_7d", sa.Float(), nullable=True),
        sa.Column("backlog_ratio", sa.Float(), nullable=False),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_daily_plans_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "local_date", name=op.f("pk_daily_plans")),
    )
    op.create_table(
        "kana",
        sa.Column("char", sa.String(length=4), nullable=False),
        sa.Column("script", sa.Enum("hiragana", "katakana", name="kana_script"), nullable=False),
        sa.Column("romaji_key", sa.String(length=8), nullable=False),
        sa.Column("cyrillic", sa.String(length=8), nullable=False),
        sa.Column("row", sa.String(length=8), nullable=False),
        sa.Column("kind", sa.Enum("basic", "dakuten", "handakuten", "yoon", name="kana_kind"), nullable=False),
        sa.Column("group_order", sa.Integer(), nullable=False),
        sa.Column("mnemonic_ru", sa.String(length=512), nullable=True),
        sa.Column("example_word", sa.String(length=32), nullable=True),
        sa.Column("example_reading", sa.String(length=32), nullable=True),
        sa.Column("example_gloss_ru", sa.String(length=128), nullable=True),
        sa.Column("audio_asset_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["audio_asset_id"],
            ["audio_assets.id"],
            name=op.f("fk_kana_audio_asset_id_audio_assets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kana")),
        sa.UniqueConstraint("script", "char", name=op.f("uq_kana_script_char")),
    )
    op.create_index(op.f("ix_kana_group_order"), "kana", ["group_order"], unique=False)
    op.create_table(
        "learning_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("client", sa.Enum("bot", "miniapp", name="session_client"), nullable=False),
        sa.Column("planned_steps", sa.Integer(), nullable=False),
        sa.Column("completed_steps", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.Enum("in_progress", "completed", "abandoned", name="session_outcome"), nullable=False),
        sa.Column("active_ms", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_learning_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_sessions")),
    )
    op.create_index("ix_learning_sessions_user_date", "learning_sessions", ["user_id", "local_date"], unique=False)
    op.create_table(
        "streaks",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("current", sa.Integer(), nullable=False),
        sa.Column("longest", sa.Integer(), nullable=False),
        sa.Column("last_active_date", sa.Date(), nullable=True),
        sa.Column("freezes_available", sa.Integer(), nullable=False),
        sa.Column("freeze_earned_week", sa.String(length=16), nullable=True),
        sa.Column("freeze_used_dates", postgresql.ARRAY(sa.Date()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_streaks_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_streaks")),
    )
    op.create_table(
        "session_steps",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "review_recog",
                "review_prod",
                "intro_item",
                "cloze",
                "listen_choose",
                "shadow",
                "speak",
                "roleplay",
                "wrapup",
                name="step_kind",
            ),
            nullable=False,
        ),
        sa.Column("card_id", sa.Uuid(), nullable=True),
        sa.Column("item_id", sa.Uuid(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Enum("pending", "shown", "answered", "skipped", name="step_status"), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("shown_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tg_message_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"], ["cards.id"], name=op.f("fk_session_steps_card_id_cards"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name=op.f("fk_session_steps_item_id_items"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["learning_sessions.id"],
            name=op.f("fk_session_steps_session_id_learning_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_steps")),
        sa.UniqueConstraint("session_id", "idx", name=op.f("uq_session_steps_session_id_idx")),
    )
    op.create_index("ix_session_steps_session_status", "session_steps", ["session_id", "status"], unique=False)
    op.add_column("cards", sa.Column("step", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cards", "step")
    op.drop_index("ix_session_steps_session_status", table_name="session_steps")
    op.drop_table("session_steps")
    op.drop_table("streaks")
    op.drop_index("ix_learning_sessions_user_date", table_name="learning_sessions")
    op.drop_table("learning_sessions")
    op.drop_index(op.f("ix_kana_group_order"), table_name="kana")
    op.drop_table("kana")
    op.drop_table("daily_plans")
    for enum_name in ("step_status", "step_kind", "session_outcome", "session_client", "kana_kind", "kana_script"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # ### end Alembic commands ###
