"""phase 2: vocab_lemmas

Schema only. Content arrives through ``nihongo-content import-vocab`` from
``backend/data/seed/vocab_core.json`` — never through a migration, per rule 2 of docs/CONTENT.md.

``items.type`` already offers ``vocab`` and ``items.stage`` already offers ``core``: both enums were
created complete in the baseline, so no enum needs altering here.

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-18 14:31:27.364264
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0007"
down_revision: str | Sequence[str] | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vocab_lemmas",
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("word", sa.String(length=64), nullable=False),
        sa.Column("reading", sa.String(length=64), nullable=False),
        sa.Column("gloss_ru", sa.String(length=512), nullable=False),
        sa.Column("pos", sa.String(length=32), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("example_ja", sa.String(length=256), nullable=True),
        sa.Column("example_reading", sa.String(length=256), nullable=True),
        sa.Column("example_gloss_ru", sa.String(length=512), nullable=True),
        sa.Column("gloss_source", sa.String(length=16), nullable=False),
        sa.Column("gloss_review_status", sa.String(length=16), nullable=False),
        sa.Column("jlpt_level", sa.Integer(), nullable=True),
        sa.Column("freq_rank", sa.Integer(), nullable=True),
        sa.Column("pitch_pattern", sa.String(length=32), nullable=True),
        sa.Column("jmdict_seq", sa.Integer(), nullable=True),
        sa.Column("kanji_forms", postgresql.ARRAY(sa.String(length=64)), nullable=True),
        sa.Column("audio_asset_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["audio_asset_id"],
            ["audio_assets.id"],
            name=op.f("fk_vocab_lemmas_audio_asset_id_audio_assets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vocab_lemmas")),
        sa.UniqueConstraint("slug", name=op.f("uq_vocab_lemmas_slug")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vocab_lemmas")
    # ### end Alembic commands ###
